# -*- coding: utf-8 -*-
"""Los once mundos, en un solo sitio. De aquí salen el borrador y el paquete
que se lleva al repositorio, así que no pueden decirse cosas distintas."""
import re

def svg(ruta):
    s = open("svg/" + ruta, encoding="utf-8").read()
    s = re.sub(r"<!--.*?-->", "", s, flags=re.S)
    s = re.sub(r"\s+", " ", s).strip().replace('"', "'")
    for a, b in [("%","%25"),("#","%23"),("<","%3C"),(">","%3E"),("&","%26"),("?","%3F")]:
        s = s.replace(a, b)
    return "data:image/svg+xml," + s

# familia: de-aqui | de-pantalla | de-materia
MUNDOS = [
 dict(id="talavera", nombre="Talavera", familia="de-aqui", llave="Loza vidriada", color="#1e3f8f",
  premisa="Loza vidriada. Fuera la vid de arriba: no terminaba de conectar y le robaba sitio al texto. Lo que hace la pieza es el BORDE DOBLE —cobalto, respiro blanco, cobalto— como el filo pintado de un plato. El azulejo de flores se queda en el fondo, que es donde no estorba, y el icono es una flor de cinco pétalos. Sin serif: Alegreya Sans conserva el calor de la familia y se lee mejor a tamaño pequeño.",
  letra="Alegreya Sans", ancho="−14%", escala="1", esquinas="14 px · suaves", peso="~110 KB", horas="Las dos",
  tokens={"--m-pagina":"#e4d9c1","--m-grano":f'url("{svg("azulejo.svg")}")',"--m-grano-op":".3",
   "--m-tarjeta":"#fdfbf5","--m-borde":"1.5px","--m-borde-color":"#1e3f8f",
   "--m-sombra":"inset 0 0 0 3px #fdfbf5, inset 0 0 0 4.5px rgba(30,63,143,.55), 0 5px 16px rgba(30,63,143,.2)",
   "--m-r-tarjeta":"14px","--m-r-mini":"999px","--m-r-barra":"999px","--m-r-chip":"999px",
   "--m-tinta":"#0d2044","--m-tinta-2":"#465a76",
   "--m-acento":"#1e3f8f","--m-acento-velo":"rgba(30,63,143,.11)",
   "--m-aviso":"#7a5a00","--m-aviso-velo":"rgba(122,90,0,.13)",
   "--m-peligro":"#9e2f14","--m-peligro-velo":"rgba(158,47,20,.12)","--m-carril":"#d7ddea",
   "--m-icono":f'url("{svg("flor-icono.svg")}") center/contain no-repeat',
   "--m-titulo":'"Alegreya Sans",system-ui,sans-serif',"--m-titulo-px":"16px","--m-titulo-peso":"800",
   "--m-cifra":'"Alegreya Sans",system-ui,sans-serif',"--m-cifra-peso":"800","--m-cifra-esp":"-.02em",
   "--m-chip-fuente":'"Alegreya Sans",system-ui,sans-serif',"--m-chip-peso":"700",
   "--m-dur":".7s","--m-curva":"cubic-bezier(.25,.9,.35,1)"}),

 dict(id="grabado", nombre="Grabado", familia="de-aqui", llave="El de las calaveras", color="#a32615",
  premisa="Una tinta negra sobre papel de periódico y el rojo de la segunda pasada para lo que importa. La tarjeta es una plancha: borde negro grueso, sombra dura desplazada y cero difuminado — y al pasar el cursor se apoya, la sombra se cierra y el papel baja, como cuando bajas la plancha sobre la hoja. La letra de madera se fue: Outfit en negrita se lee de un vistazo y no compite con el rayado.",
  letra="Outfit", ancho="+0%", escala="1", esquinas="0 px · vivas", peso="~35 KB", horas="Día",
  tokens={"--m-pagina":"#e3ddcd",
   "--m-grano":"repeating-linear-gradient(52deg, rgba(24,20,16,.13) 0 1px, transparent 1px 5px), url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='200' height='200'%3E%3Cfilter id='p'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.85' numOctaves='3'/%3E%3C/filter%3E%3Crect width='200' height='200' filter='url(%23p)'/%3E%3C/svg%3E\")",
   "--m-grano-op":".22","--m-tarjeta":"#efe9da","--m-borde":"2px","--m-borde-color":"#181410",
   "--m-sombra":"7px 7px 0 #181410","--m-sombra-encima":"2px 2px 0 #181410","--m-empuje":"5px",
   "--m-r-tarjeta":"0","--m-r-mini":"0","--m-r-barra":"0","--m-r-chip":"0",
   "--m-tinta":"#181410","--m-tinta-2":"#5c5346",
   "--m-acento":"#a32615","--m-acento-velo":"rgba(163,38,21,.13)",
   "--m-aviso":"#6b5200","--m-aviso-velo":"rgba(107,82,0,.14)",
   "--m-peligro":"#181410","--m-peligro-velo":"rgba(24,20,16,.13)","--m-carril":"#cec5b0",
   "--m-icono":"repeating-linear-gradient(45deg,#181410 0 2px,#efe9da 2px 4px)",
   "--m-titulo":'"Outfit",system-ui,sans-serif',"--m-titulo-px":"16px","--m-titulo-peso":"700","--m-titulo-esp":"-.01em",
   "--m-cifra":'"Outfit",system-ui,sans-serif',"--m-cifra-peso":"700","--m-cifra-esp":"-.03em",
   "--m-chip-fuente":'"Outfit",system-ui,sans-serif',"--m-chip-peso":"700","--m-chip-esp":".06em","--m-chip-caja":"uppercase",
   "--m-dur":".16s","--m-curva":"cubic-bezier(.2,.8,.3,1)"}),

 dict(id="rotulo", nombre="Rótulo", familia="de-aqui", llave="El de la calle", color="#ff3d8b",
  premisa="Rehecho entero. La letra anterior era redonda y blanda y el mundo salía a goma de mascar; ahora va condensada y pesada con sombra dura, que es como se rotula de verdad sobre lámina. Y arriba, en vez de adorno, el FILETE: raya gorda, respiro, raya fina pintada a pulso con su temblor, y tres puntos. Esmalte sobre metal, rosa mexicano contra azul petróleo.",
  letra="Anton", ancho="−13%", escala="1", esquinas="16 px · redondeadas", peso="~80 KB", horas="Noche",
  tokens={"--m-pagina":"#0e3040",
   "--m-grano":"linear-gradient(103deg, rgba(255,255,255,.09) 0 16%, transparent 20% 76%, rgba(255,255,255,.05) 82%)",
   "--m-grano-op":"1","--m-tarjeta":"linear-gradient(168deg,#14455a 0%,#0f3548 60%,#134256 100%)",
   "--m-borde":"3px","--m-borde-color":"#f2e7cf",
   "--m-sombra":"4px 4px 0 rgba(0,0,0,.55), inset 0 1px 0 rgba(255,255,255,.14)",
   "--m-r-tarjeta":"16px","--m-r-mini":"999px","--m-r-barra":"999px","--m-r-chip":"999px",
   "--m-cenefa-alto":"20px","--m-cenefa":f'url("{svg("rotulo-marco.svg")}") repeat-x',
   "--m-tinta":"#fdf6e6","--m-tinta-2":"#adc6d2","--m-titulo-sombra":"2px 2px 0 rgba(0,0,0,.65)",
   "--m-acento":"#ff3d8b","--m-acento-tinta":"#ffa3cd","--m-acento-velo":"rgba(255,61,139,.17)",
   "--m-aviso":"#ffd447","--m-aviso-velo":"rgba(255,212,71,.16)",
   "--m-peligro":"#ff8a70","--m-peligro-velo":"rgba(255,138,112,.16)","--m-carril":"#0a2634",
   "--m-icono":"radial-gradient(circle at 36% 30%,#ff85b6,#d4145a)",
   "--m-titulo":'"Anton",Impact,sans-serif',"--m-titulo-px":"18px","--m-titulo-peso":"400","--m-titulo-esp":".01em",
   "--m-cifra":'"Anton",Impact,sans-serif',"--m-cifra-peso":"400","--m-cifra-esp":".01em",
   "--m-chip-fuente":'"Anton",Impact,sans-serif',"--m-chip-esp":".08em","--m-chip-caja":"uppercase",
   "--m-dur":".34s","--m-curva":"cubic-bezier(.34,1.5,.64,1)"},
  extra=".rotulo .ficha{ padding-top:32px; }"),

 dict(id="picado", nombre="Papel picado", familia="de-aqui", llave="El de fiesta", color="#c2145f",
  premisa="Ahora sí es papel picado y no una idea de papel picado: el fondo son las hojas colgando del hilo, con su calado por dentro —rombo, medias lunas, agujeros— y su FLECO recortado abajo, en rosa y turquesa como en la calle. La tarjeta también termina en fleco, porque una hoja de papel picado no acaba en línea recta. Letra de bloque, que es como se recorta una letra a tijera.",
  letra="Archivo Black", ancho="+19%", escala="0.94", esquinas="5 px · casi vivas", peso="~85 KB", horas="Día",
  tokens={"--m-pagina":"#f5eee1",
   "--m-grano":f'url("{svg("picado-banda.svg")}")',
   "--m-grano-op":".5","--m-tarjeta":"#fffdf8","--m-borde":"1px","--m-borde-color":"#e0d3bd",
   "--m-sombra":"0 6px 16px rgba(120,90,60,.15)",
   "--m-r-tarjeta":"5px","--m-r-mini":"999px","--m-r-barra":"999px","--m-r-chip":"999px",
   "--m-fleco-alto":"14px","--m-fleco":f'url("{svg("picado-fleco.svg")}") repeat-x',
   "--m-tinta":"#3a2438","--m-tinta-2":"#7a6070",
   "--m-acento":"#c2145f","--m-acento-velo":"rgba(194,20,95,.11)",
   "--m-aviso":"#7d5a00","--m-aviso-velo":"rgba(125,90,0,.13)",
   "--m-peligro":"#a02a12","--m-peligro-velo":"rgba(160,42,18,.12)","--m-carril":"#e7dcc9",
   "--m-icono":"conic-gradient(#e6187c 0 25%, #2aa9a0 0 50%, #f2a516 0 75%, #6d3fb8 0)",
   "--m-titulo":'"Archivo Black",system-ui,sans-serif',"--m-titulo-px":"14px","--m-titulo-peso":"400","--m-titulo-esp":"-.01em",
   "--m-cifra":'"Archivo Black",system-ui,sans-serif',"--m-cifra-peso":"400","--m-cifra-esp":"-.03em",
   "--m-chip-fuente":'"Archivo Black",system-ui,sans-serif',"--m-chip-esp":".04em",
   "--m-dur":".5s","--m-curva":"cubic-bezier(.34,1.45,.64,1)"},
  extra=".picado .ficha{ padding-bottom:24px; }"),

 dict(id="consola", nombre="Consola", familia="de-pantalla", llave="Gratis, siempre", color="#3bff9e",
  premisa="Fósforo sobre negro, todo en monoespaciada, cero adornos y el movimiento a saltos en vez de suave. Es el único que no necesita ni una imagen: la textura son dos líneas de CSS. Y de paso es la red de seguridad para quien no distingue bien los tonos.",
  letra="JetBrains Mono", ancho="+29%", escala="0.86", esquinas="0 px · vivas", peso="~28 KB", horas="Noche",
  tokens={"--m-pagina":"#000",
   "--m-grano":"repeating-linear-gradient(180deg, rgba(120,255,190,.16) 0 1px, transparent 1px 3px)",
   "--m-grano-op":"1","--m-tarjeta":"#050705","--m-borde":"1px","--m-borde-color":"#2f5f47",
   "--m-sombra":"none","--m-r-tarjeta":"0","--m-r-mini":"0","--m-r-barra":"0","--m-r-chip":"0",
   "--m-tinta":"#c9ffe4","--m-tinta-2":"#5f9a7d",
   "--m-acento":"#3bff9e","--m-acento-velo":"rgba(59,255,158,.12)",
   "--m-aviso":"#ffd447","--m-aviso-velo":"rgba(255,212,71,.12)",
   "--m-peligro":"#ff6b52","--m-peligro-velo":"rgba(255,107,82,.12)","--m-carril":"#10291d",
   "--m-icono":"#3bff9e",
   "--m-titulo":'"JetBrains Mono",ui-monospace,monospace',"--m-titulo-px":"13px","--m-titulo-peso":"700",
   "--m-cifra":'"JetBrains Mono",ui-monospace,monospace',"--m-cifra-peso":"700","--m-cifra-esp":"-.04em",
   "--m-chip-fuente":'"JetBrains Mono",ui-monospace,monospace',"--m-chip-esp":".06em","--m-chip-caja":"uppercase",
   "--m-dur":".12s","--m-curva":"steps(12, end)"}),

 dict(id="neon", nombre="Neón", familia="de-pantalla", llave="Todo redondo", color="#3febff",
  premisa="Un tubo de neón es vidrio DOBLADO, así que aquí todo es redondo — la tarjeta, la barra, las pastillas. Cian sobre asfalto mojado, con el resplandor por dentro y por fuera del trazo. El aviso pasa a ámbar y el peligro a rosa encendido: cambian de tono y siguen diciendo lo mismo.",
  letra="Baloo 2", ancho="−2%", escala="1", esquinas="Redondas del todo", peso="~60 KB", horas="Noche",
  tokens={"--m-pagina":"#08060f",
   "--m-grano":"radial-gradient(ellipse at 22% 12%, rgba(255,45,150,.2), transparent 55%), radial-gradient(ellipse at 82% 78%, rgba(60,235,255,.16), transparent 52%)",
   "--m-grano-op":"1","--m-tarjeta":"linear-gradient(170deg,#141024 0%,#0d0a18 100%)",
   "--m-borde":"2px","--m-borde-color":"#3febff",
   "--m-sombra":"0 0 0 1px rgba(63,235,255,.28), 0 0 18px rgba(63,235,255,.34), inset 0 0 16px rgba(63,235,255,.12)",
   "--m-halo":"0 0 10px rgba(63,235,255,.75)",
   "--m-r-tarjeta":"999px","--m-r-mini":"999px","--m-r-barra":"999px","--m-r-chip":"999px",
   "--m-tinta":"#eafcff","--m-tinta-2":"#8fb8c4","--m-titulo-sombra":"0 0 12px rgba(63,235,255,.6)",
   "--m-acento":"#3febff","--m-acento-tinta":"#7df3ff","--m-acento-velo":"rgba(63,235,255,.14)",
   "--m-aviso":"#ffc24d","--m-aviso-velo":"rgba(255,194,77,.15)",
   "--m-peligro":"#ff5f8f","--m-peligro-velo":"rgba(255,95,143,.15)","--m-carril":"#191430",
   "--m-icono":"radial-gradient(circle at 38% 34%, #ff8fc4, #ff2d96 62%, #7a0f47)",
   "--m-titulo":'"Baloo 2",system-ui,sans-serif',"--m-titulo-px":"15px","--m-titulo-peso":"700",
   "--m-cifra":'"Baloo 2",system-ui,sans-serif',"--m-cifra-peso":"700","--m-cifra-esp":"-.01em",
   "--m-chip-fuente":'"Baloo 2",system-ui,sans-serif',"--m-dur":".9s","--m-curva":"cubic-bezier(.18,.9,.3,1)"},
  extra=".neon .ficha{ padding:16px 22px; }"),

 dict(id="cyber", nombre="Cyberpunk", familia="de-pantalla", llave="Visor, no marco", color="#00f0ff",
  premisa="El visor, no el letrero: la tarjeta no lleva marco cerrado —lleva cuatro escuadras y una regla de marcas, como una mira—, la esquina de abajo va cortada en chaflán de verdad y el título sale desdoblado como una señal mal sincronizada. La paleta sí es la del género: amarillo ácido sobre negro con el cian de los datos. Un color no es de nadie; lo que sí sería de alguien es su nombre, su logotipo o su tipografía, y de eso no hay nada aquí.",
  letra="Chakra Petch", ancho="+4%", escala="1", esquinas="0 px + chaflán", peso="~70 KB", horas="Noche",
  nota="Los colores no se registran; lo que se registra es un nombre, un logotipo o una tipografía. Aquí no hay ninguno de los tres.",
  tokens={"--m-pagina":"#05070c",
   "--m-grano":"repeating-linear-gradient(180deg, rgba(252,238,10,.05) 0 1px, transparent 1px 4px), radial-gradient(ellipse at 78% 16%, rgba(0,229,255,.16), transparent 56%), radial-gradient(ellipse at 14% 84%, rgba(252,238,10,.12), transparent 52%)",
   "--m-grano-op":"1","--m-tarjeta":"linear-gradient(180deg,#12130a 0%,#080905 100%)",
   "--m-borde":"0","--m-borde-color":"transparent","--m-sombra":"none",
   "--m-r-tarjeta":"0","--m-r-mini":"0","--m-r-barra":"0","--m-r-chip":"0",
   "--m-tinta":"#f2f7d8","--m-tinta-2":"#93a06a",
   "--m-titulo-sombra":"1.5px 0 0 rgba(255,46,110,.8), -1.5px 0 0 rgba(0,229,255,.8)",
   "--m-acento":"#fcee0a","--m-acento-velo":"rgba(252,238,10,.13)",
   "--m-aviso":"#ff7a1a","--m-aviso-velo":"rgba(255,122,26,.15)",
   "--m-peligro":"#ff2e6e","--m-peligro-velo":"rgba(255,46,110,.15)","--m-carril":"#1a1a08",
   "--m-icono":f'url("{svg("hud-reticula.svg")}") center/contain no-repeat',
   "--m-titulo":'"Chakra Petch",system-ui,sans-serif',"--m-titulo-px":"15px","--m-titulo-peso":"700","--m-titulo-esp":".04em","--m-titulo-caja":"uppercase",
   "--m-cifra":'"Chakra Petch",system-ui,sans-serif',"--m-cifra-peso":"700","--m-cifra-esp":"0",
   "--m-chip-fuente":'"Chakra Petch",system-ui,sans-serif',"--m-chip-esp":".1em","--m-chip-caja":"uppercase",
   "--m-dur":".18s","--m-curva":"steps(9,end)"},
  extra=""".cyber .ficha{
    background-image:url("%s"), linear-gradient(180deg,#12130a 0%%,#080905 100%%);
    background-size:100%% 100%%, auto; background-repeat:no-repeat;
    clip-path:polygon(0 0, 100%% 0, 100%% calc(100%% - 14px), calc(100%% - 14px) 100%%, 0 100%%);
    padding:20px 18px 18px;
  }""" % svg("hud-esquinas.svg")),

 dict(id="plano", nombre="Blueprint", familia="de-pantalla", llave="Nada está terminado", color="#9fd0ff",
  premisa="El plano azul de toda la vida: retícula de dos pesos, cotas con puntas de flecha y marcas de sección. Aquí la tarjeta no es una tarjeta: es una PIEZA ACOTADA, con su línea de medida cruzando por encima y el hueco donde iría la cifra. Dice algo que ningún otro mundo dice — que lo tuyo todavía se está construyendo.",
  letra="Rajdhani", ancho="−10%", escala="1", esquinas="0 px · vivas", peso="~65 KB", horas="Noche",
  nota="La tarjeta era casi transparente y el texto se peleaba con la retícula del fondo. Ahora es un panel opaco: la retícula se ve alrededor, no por debajo de lo que hay que leer.",
  tokens={"--m-pagina":"#0d2b52",
   "--m-grano":f'url("{svg("plano-rejilla.svg")}")',"--m-grano-op":"1",
   "--m-tarjeta":"rgba(6,26,52,.9)","--m-borde":"1px","--m-borde-color":"#6ea2d8",
   "--m-sombra":"inset 0 0 0 4px rgba(6,26,52,.95), inset 0 0 0 5px rgba(110,162,216,.5), 0 8px 22px rgba(0,0,0,.35)",
   "--m-r-tarjeta":"0","--m-r-mini":"0","--m-r-barra":"0","--m-r-chip":"0",
   "--m-cenefa-alto":"26px","--m-cenefa":f'url("{svg("plano-cota.svg")}") center/200px 26px no-repeat',
   "--m-tinta":"#eaf4ff","--m-tinta-2":"#8fb6db",
   "--m-acento":"#9fd0ff","--m-acento-velo":"rgba(159,208,255,.13)",
   "--m-aviso":"#ffd98a","--m-aviso-velo":"rgba(255,217,138,.14)",
   "--m-peligro":"#ff9c86","--m-peligro-velo":"rgba(255,156,134,.14)","--m-carril":"rgba(159,208,255,.16)",
   "--m-icono":f'url("{svg("plano-marca.svg")}") center/contain no-repeat',
   "--m-titulo":'"Rajdhani",system-ui,sans-serif',"--m-titulo-px":"17px","--m-titulo-peso":"700","--m-titulo-esp":".03em",
   "--m-cifra":'"Rajdhani",system-ui,sans-serif',"--m-cifra-peso":"700","--m-cifra-esp":"0",
   "--m-chip-fuente":'"Rajdhani",system-ui,sans-serif',"--m-chip-esp":".1em","--m-chip-caja":"uppercase",
   "--m-dur":".4s","--m-curva":"cubic-bezier(.4,0,.2,1)"},
  extra=".plano .ficha{ padding-top:36px; }"),

 dict(id="forja", nombre="Forja", familia="de-materia", llave="El buque insignia", color="#ff9d3d",
  premisa="Hierro golpeado con la brasa todavía dentro: banda remachada arriba —remaches a intervalos irregulares, que uno cada 16 px exactos parece tornillería de mueble— y una voluta de herrería en la esquina, de esas que salen cuando al herrero le sobra hierro. Esquina viva en todo y la letra grabada en vez de escrita.",
  letra="Cinzel", ancho="+28%", escala="0.88", esquinas="0 px · vivas", peso="~180 KB", horas="Noche",
  tokens={"--m-pagina":"#16110c",
   "--m-grano":"url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='180' height='180'%3E%3Cfilter id='f'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.035 0.09' numOctaves='4'/%3E%3C/filter%3E%3Crect width='180' height='180' filter='url(%23f)'/%3E%3C/svg%3E\")",
   "--m-grano-op":".16","--m-tarjeta":"linear-gradient(163deg, #2a2016 0%, #1d1710 55%, #241b13 100%)",
   "--m-borde":"3px","--m-borde-color":"#6b5636",
   "--m-marco":"linear-gradient(150deg,#8a6f3f,#d8b978 18%,#3a2e1c 48%,#a08551 78%,#40331e) 1",
   "--m-sombra":"inset 0 1px 0 rgba(255,214,150,.13), 0 10px 24px rgba(0,0,0,.5)",
   "--m-r-tarjeta":"0","--m-r-mini":"0","--m-r-barra":"0","--m-r-chip":"0",
   "--m-cenefa-alto":"14px","--m-cenefa":f'url("{svg("forja-remaches.svg")}") repeat-x',
   "--m-tinta":"#f2e3ce","--m-tinta-2":"#a99372",
   "--m-acento":"#ff9d3d","--m-acento-velo":"rgba(255,157,61,.15)",
   "--m-aviso":"#f5d76e","--m-aviso-velo":"rgba(245,215,110,.15)",
   "--m-peligro":"#ff8a70","--m-peligro-velo":"rgba(255,138,112,.15)","--m-carril":"#3a2d1d",
   "--m-icono":"linear-gradient(150deg,#c98a3a,#8a5622)",
   "--m-titulo":'"Cinzel",Georgia,serif',"--m-titulo-px":"14px","--m-titulo-peso":"700","--m-titulo-esp":".04em",
   "--m-cifra":'"Cinzel",Georgia,serif',"--m-cifra-peso":"700","--m-cifra-esp":"0",
   "--m-chip-fuente":'"Cinzel",Georgia,serif',"--m-chip-esp":".07em",
   "--m-dur":"1.1s","--m-curva":"cubic-bezier(.16,.84,.28,1)"},
  extra=""".forja .ficha{ padding-top:26px; }
  .forja .ficha::after{
    content:""; position:absolute; right:-2px; bottom:-2px; width:46px; height:46px;
    background:url("%s") center/contain no-repeat; transform:scaleX(-1) rotate(-90deg);
    transform-origin:center; pointer-events:none; opacity:.9;
  }""" % svg("forja-voluta.svg")),

 dict(id="obsidiana", nombre="Obsidiana", familia="de-materia", llave="El oscuro elegante", color="#3fd0c9",
  premisa="Rehecho a lo que es la piedra: grises y negros, y el color contado con los dedos. La obsidiana no se parte en rectas, se parte en ondas de concha que salen del punto del golpe — eso es el fondo, arcos anidados desde una esquina. El icono es una esquirla de tres planos con un solo filo brillante, y la iridiscencia son DOS destellos, uno verde y uno violeta, y nada más. La serif se fue: aquí va una geométrica fría, que es lo que pide un vidrio.",
  letra="Sora", ancho="+13%", escala="0.99", esquinas="0 px · vivas", peso="~80 KB", horas="Noche",
  tokens={"--m-pagina":"#07080a",
   "--m-grano":f'url("{svg("obsidiana-fractura.svg")}")',
   "--m-grano-op":".85","--m-tarjeta":"linear-gradient(124deg,#1a1e23 0 32%,#0a0c0f 32% 61%,#141820 61%)",
   "--m-borde":"1px","--m-borde-color":"#333c44",
   "--m-sombra":"inset 0 1px 0 rgba(215,228,235,.22), inset 0 -1px 0 rgba(0,0,0,.8), 0 16px 38px rgba(0,0,0,.72)",
   "--m-r-tarjeta":"0","--m-r-mini":"0","--m-r-barra":"0","--m-r-chip":"0",
   "--m-tinta":"#eef3f5","--m-tinta-2":"#8d979e",
   "--m-acento":"#c3ced5","--m-acento-velo":"rgba(195,206,213,.1)",
   "--m-aviso":"#d8c07a","--m-aviso-velo":"rgba(216,192,122,.12)",
   "--m-peligro":"#d98a7c","--m-peligro-velo":"rgba(217,138,124,.13)","--m-carril":"#191d22",
   "--m-icono":f'url("{svg("obsidiana-filo.svg")}") center/contain no-repeat',
   "--m-titulo":'"Sora",system-ui,sans-serif',"--m-titulo-px":"14px","--m-titulo-peso":"600","--m-titulo-esp":"-.01em",
   "--m-cifra":'"Sora",system-ui,sans-serif',"--m-cifra-peso":"600","--m-cifra-esp":"-.04em",
   "--m-chip-fuente":'"Sora",system-ui,sans-serif',"--m-chip-peso":"600","--m-chip-esp":".07em","--m-chip-caja":"uppercase",
   "--m-dur":"1.2s","--m-curva":"cubic-bezier(.2,.9,.25,1)"}),

 dict(id="cenit", nombre="Cénit", familia="de-materia", llave="Antes «Vitral»", color="#f0dcb4",
  premisa="El vitral se fue al cielo, que es donde el estilo quería estar: los mismos añiles y el mismo oro, pero ahora son ESTRELLAS y las líneas que las unen. Y unen solo algunas, con huecos a propósito — si se unieran todas sería una malla; una constelación es un dibujo que alguien decidió ver. El icono es una estrella de cuatro brazos con cintura, la del cielo antiguo. Pesa un tercio de lo que pesaba el plomo.",
  letra="Julius Sans One", ancho="+23%", escala="0.91", esquinas="3 px · casi vivas", peso="~80 KB", horas="Noche",
  tokens={"--m-pagina":"#0c1030",
   "--m-grano":f'url("{svg("cenit-constelacion.svg")}")',
   "--m-grano-op":"1","--m-tarjeta":"linear-gradient(158deg, #171d46 0%, #0f1332 62%, #191e4e 100%)",
   "--m-borde":"1px","--m-borde-color":"#d8b878",
   "--m-sombra":"inset 0 0 0 4px rgba(15,19,50,.9), inset 0 0 0 5px rgba(216,184,120,.35), 0 14px 34px rgba(0,0,0,.55)",
   "--m-r-tarjeta":"3px","--m-r-mini":"3px","--m-r-barra":"0","--m-r-chip":"3px",
   "--m-tinta":"#eeecff","--m-tinta-2":"#a0a3d2",
   "--m-acento":"#f0dcb4","--m-acento-velo":"rgba(240,220,180,.13)",
   "--m-aviso":"#ffd98a","--m-aviso-velo":"rgba(255,217,138,.14)",
   "--m-peligro":"#ff9db0","--m-peligro-velo":"rgba(255,157,176,.15)","--m-carril":"#20254e",
   "--m-icono":f'url("{svg("cenit-astro.svg")}") center/contain no-repeat',
   "--m-titulo":'"Julius Sans One",system-ui,sans-serif',"--m-titulo-px":"15px","--m-titulo-peso":"400","--m-titulo-esp":".08em","--m-titulo-caja":"uppercase",
   "--m-cifra":'"Julius Sans One",system-ui,sans-serif',"--m-cifra-peso":"400","--m-cifra-esp":".01em",
   "--m-chip-fuente":'"Julius Sans One",system-ui,sans-serif',"--m-chip-esp":".13em","--m-chip-caja":"uppercase",
   "--m-dur":"1.4s","--m-curva":"cubic-bezier(.22,1,.36,1)"}),

 dict(id="averno", nombre="Averno", familia="de-relato", llave="El oscuro de verdad", color="#ff7a3d",
  premisa="Piedra quemada con la brasa debajo. Del poema se cita lo único que hay que citar —los círculos—: arcos concéntricos que se estrechan al bajar y solo el de dentro sigue ardiendo. Cae ceniza en el fondo, con tres motas que todavía no se han apagado, y el icono es un sol eclipsado: anillo encendido y centro muerto. Nada de cuernos ni pentagramas — el infierno de ese libro es un lugar, no un disfraz.",
  letra="Grenze Gotisch", ancho="−17%", escala="1", esquinas="2 px · piedra tallada", peso="~95 KB", horas="Noche",
  tokens={"--m-pagina":"radial-gradient(ellipse 115% 58% at 50% 120%, #5a2109 0%, #180b06 52%, #050302 100%)",
   "--m-grano":f'url("{svg("averno-ceniza.svg")}")',"--m-grano-op":".9",
   "--m-tarjeta":"linear-gradient(180deg,#1d0f0b 0%,#0a0605 100%)",
   "--m-borde":"1px","--m-borde-color":"#4a2418",
   "--m-sombra":"inset 0 1px 0 rgba(255,150,80,.16), 0 12px 30px rgba(0,0,0,.62)",
   "--m-r-tarjeta":"2px","--m-r-mini":"2px","--m-r-barra":"2px","--m-r-chip":"2px",
   "--m-tinta":"#f2ded1","--m-tinta-2":"#a68873",
   "--m-acento":"#ff7a3d","--m-acento-velo":"rgba(255,122,61,.14)",
   "--m-aviso":"#f0c24a","--m-aviso-velo":"rgba(240,194,74,.14)",
   "--m-peligro":"#ff3b6b","--m-peligro-velo":"rgba(255,59,107,.15)","--m-carril":"#1a0c08",
   "--m-icono":f'url("{svg("averno-sello.svg")}") center/contain no-repeat',
   "--m-titulo":'"Grenze Gotisch",Georgia,serif',"--m-titulo-px":"17px","--m-titulo-peso":"700","--m-titulo-esp":".01em",
   "--m-cifra":'"Grenze Gotisch",Georgia,serif',"--m-cifra-peso":"700","--m-cifra-esp":"0",
   "--m-chip-fuente":'"Grenze Gotisch",Georgia,serif',"--m-chip-esp":".05em",
   "--m-dur":"1.3s","--m-curva":"cubic-bezier(.15,.8,.25,1)"},
  extra=""".averno .ficha{ overflow:hidden; }
  .averno .ficha::after{
    content:""; position:absolute; right:0; bottom:0; width:120px; height:120px;
    background:url("%s") right bottom/contain no-repeat; opacity:.75; pointer-events:none;
  }""" % svg("averno-anillos.svg")),

 dict(id="ventisca", nombre="Ventisca", familia="de-relato", llave="Frío con una hoguera", color="#8fd4ff",
  premisa="Chapa de hierro a la intemperie y el hielo ganándole terreno: dendritas de verdad creciendo desde las esquinas —tallo que avanza y ramas al mismo ángulo a los dos lados, que es lo que hace el hielo— y un filo de agujas colgando del borde de arriba. La interfaz es de hielo; el calor está detrás, en el resplandor ámbar que sube desde abajo de la pantalla. Esa tensión ES el mundo.",
  letra="Big Shoulders Display", ancho="−26%", escala="1", esquinas="3 px · chapa", peso="~90 KB", horas="Noche",
  tokens={"--m-pagina":"radial-gradient(ellipse 130% 55% at 50% 112%, #6b3a12 0%, #17222c 48%, #0d151d 100%)",
   "--m-grano":"radial-gradient(ellipse 90% 60% at 50% -10%, rgba(190,230,255,.14), transparent 60%)",
   "--m-grano-op":"1","--m-tarjeta":"linear-gradient(180deg,#1e2833 0%,#141c25 100%)",
   "--m-borde":"1px","--m-borde-color":"#354654",
   "--m-sombra":"inset 0 1px 0 rgba(190,230,255,.18), 0 10px 26px rgba(0,0,0,.5)",
   "--m-r-tarjeta":"3px","--m-r-mini":"3px","--m-r-barra":"999px","--m-r-chip":"3px",
   "--m-cenefa-alto":"18px","--m-cenefa":f'url("{svg("ventisca-cristales.svg")}") repeat-x',
   "--m-tinta":"#eaf5fc","--m-tinta-2":"#93aabc",
   "--m-acento":"#8fd4ff","--m-acento-velo":"rgba(143,212,255,.13)",
   "--m-aviso":"#ffc24a","--m-aviso-velo":"rgba(255,194,74,.14)",
   "--m-peligro":"#ff7a6b","--m-peligro-velo":"rgba(255,122,107,.14)","--m-carril":"#1c2733",
   "--m-icono":f'url("{svg("ventisca-copo.svg")}") center/contain no-repeat',
   "--m-titulo":'"Big Shoulders Display",Impact,sans-serif',"--m-titulo-px":"19px","--m-titulo-peso":"700","--m-titulo-esp":".02em",
   "--m-cifra":'"Big Shoulders Display",Impact,sans-serif',"--m-cifra-peso":"700","--m-cifra-esp":".01em",
   "--m-chip-fuente":'"Big Shoulders Display",Impact,sans-serif',"--m-chip-esp":".07em","--m-chip-caja":"uppercase",
   "--m-dur":".8s","--m-curva":"cubic-bezier(.25,.85,.3,1)"},
  extra=""".ventisca .ficha{
    overflow:hidden; padding-top:28px;
    background-image:url("%s"), linear-gradient(180deg,#1e2833 0%%,#141c25 100%%);
    background-position:center top, center; background-repeat:no-repeat, no-repeat;
    background-size:110px 70px, auto;
  }""" % svg("ventisca-escarcha.svg")),

 dict(id="bastion", nombre="Bastión", familia="de-relato", llave="Blindaje", color="#4db8ff",
  premisa="Placa blindada con bisel arriba y pernos remachados en las cuatro esquinas. La franja de galones de lado a lado cansaba a los diez segundos, así que ahora es una tira de identificación: la regla de marcas calla, hay una lectura en cian, y el peligro se concentra en UN galón a la izquierda. Un aviso que está en todas partes deja de ser un aviso. El icono es una placa hexagonal con su mira.",
  letra="Michroma", ancho="+9%", escala="0.81", esquinas="4 px · placa", peso="~105 KB", horas="Noche",
  tokens={"--m-pagina":"#0e1216",
   "--m-grano":"repeating-linear-gradient(90deg, rgba(120,160,190,.05) 0 1px, transparent 1px 58px), repeating-linear-gradient(0deg, rgba(120,160,190,.05) 0 1px, transparent 1px 58px)",
   "--m-grano-op":"1","--m-tarjeta":"linear-gradient(180deg,#222b34 0%,#161d24 58%,#1a222a 100%)",
   "--m-borde":"1px","--m-borde-color":"#3c4854",
   "--m-sombra":"inset 0 1.5px 0 rgba(160,200,225,.22), inset 0 -1.5px 0 rgba(0,0,0,.55), 0 10px 26px rgba(0,0,0,.5)",
   "--m-r-tarjeta":"4px","--m-r-mini":"4px","--m-r-barra":"2px","--m-r-chip":"2px",
   "--m-cenefa-alto":"14px","--m-cenefa":f'url("{svg("bastion-tira.svg")}") repeat-x',
   "--m-tinta":"#e6f0f7","--m-tinta-2":"#8fa2b1",
   "--m-acento":"#4db8ff","--m-acento-velo":"rgba(77,184,255,.13)",
   "--m-aviso":"#ffc233","--m-aviso-velo":"rgba(255,194,51,.14)",
   "--m-peligro":"#ff5a4d","--m-peligro-velo":"rgba(255,90,77,.14)","--m-carril":"#131a21",
   "--m-icono":f'url("{svg("bastion-placa.svg")}") center/contain no-repeat',
   "--m-titulo":'"Michroma",system-ui,sans-serif',"--m-titulo-px":"11.5px","--m-titulo-peso":"400","--m-titulo-esp":".02em",
   "--m-cifra":'"Michroma",system-ui,sans-serif',"--m-cifra-peso":"400","--m-cifra-esp":"-.02em",
   "--m-chip-fuente":'"Michroma",system-ui,sans-serif',"--m-chip-esp":".06em","--m-chip-caja":"uppercase",
   "--m-dur":".3s","--m-curva":"cubic-bezier(.2,.8,.2,1)"},
  extra=""".bastion .ficha{
    padding:30px 22px 18px;
    background-image:url("%s"), url("%s"), url("%s"), url("%s"),
      linear-gradient(180deg,#222b34 0%%,#161d24 58%%,#1a222a 100%%);
    background-position:7px 22px, right 7px top 22px, 7px bottom 7px, right 7px bottom 7px, center;
    background-repeat:no-repeat; background-size:11px 11px, 11px 11px, 11px 11px, 11px 11px, auto;
  }""" % (svg("bastion-perno.svg"), svg("bastion-perno.svg"), svg("bastion-perno.svg"), svg("bastion-perno.svg"))),
]

FAMILIAS = [
 ("de-relato","De relato","No salen de una materia sino de un género: cuentan algo antes de que hagas nada. Inspirados, nunca calcados — el nombre, el marco, la letra y los dibujos son de casa."),
 ("de-aqui","De aquí","Materiales que se pueden tocar en este país. Es el hilo que ningún paquete de temas genérico puede copiar."),
 ("de-pantalla","De pantalla","No imitan una materia: imitan un aparato. Son los más baratos de todos porque casi no llevan imagen."),
 ("de-materia","De materia","Piedra, metal y vidrio. Los oscuros con cuerpo, y los más caros de hacer bien."),
]
