# -*- coding: utf-8 -*-
"""Los once mundos, en un solo sitio. De aquí salen el borrador y el paquete
que se lleva al repositorio, así que no pueden decirse cosas distintas."""
import re

def svg(ruta):
    s = open("svg/" + ruta, encoding="utf-8").read()
    s = re.sub(r"<!--.*?-->", "", s, flags=re.S)
    s = re.sub(r"\s+", " ", s).strip().replace('"', "'")
    for a, b in [("%","%25"),("#","%23"),("<","%3C"),(">","%3E"),("&","%26"),("?","%3F")]:
        s = s.replace(a, b)
    return "data:image/svg+xml," + s

# familia: de-aqui | de-pantalla | de-materia
MUNDOS = [
 dict(id="talavera", nombre="Talavera", familia="de-aqui", llave="Loza vidriada", color="#1e3f8f",
  premisa="Loza vidriada con la cenefa corriendo por arriba: una vid con hoja, capullo y gotas, ninguna en la misma posición dos veces. El icono es una flor de cinco pétalos y el borde va doble —cobalto, respiro blanco, cobalto— como el filo pintado de un plato. Esquinas suaves: la loza se moldea, no se corta.",
  letra="Alegreya", ancho="−10%", escala="1", esquinas="14 px · suaves", peso="~120 KB", horas="Las dos",
  tokens={"--m-pagina":"#eee7d8","--m-grano":f'url("{svg("azulejo.svg")}")',"--m-grano-op":".26",
   "--m-tarjeta":"#faf6ec","--m-borde":"1.5px","--m-borde-color":"#1e3f8f",
   "--m-sombra":"inset 0 0 0 3px #faf6ec, inset 0 0 0 4.5px rgba(30,63,143,.5), 0 4px 14px rgba(30,63,143,.16)",
   "--m-r-tarjeta":"14px","--m-r-mini":"999px","--m-r-barra":"999px","--m-r-chip":"999px",
   "--m-cenefa-alto":"24px","--m-cenefa":f'url("{svg("cenefa.svg")}") repeat-x',
   "--m-tinta":"#132a52","--m-tinta-2":"#5a6a86",
   "--m-acento":"#1e3f8f","--m-acento-velo":"rgba(30,63,143,.11)",
   "--m-aviso":"#7a5a00","--m-aviso-velo":"rgba(122,90,0,.13)",
   "--m-peligro":"#9e2f14","--m-peligro-velo":"rgba(158,47,20,.12)","--m-carril":"#d7ddea",
   "--m-icono":f'url("{svg("flor-icono.svg")}") center/contain no-repeat',
   "--m-titulo":'"Alegreya",Georgia,serif',"--m-titulo-px":"17px","--m-titulo-peso":"700",
   "--m-cifra":'"Alegreya",Georgia,serif',"--m-cifra-peso":"800","--m-cifra-esp":"-.02em",
   "--m-chip-fuente":'"Alegreya",Georgia,serif',"--m-dur":".7s","--m-curva":"cubic-bezier(.25,.9,.35,1)"},
  extra=".talavera .ficha{ padding-top:34px; }"),

 dict(id="grabado", nombre="Grabado", familia="de-aqui", llave="El de las calaveras", color="#a32615",
  premisa="Una sola tinta negra sobre papel de periódico, con el rojo de la segunda pasada para lo que importa. Rayado en vez de sombras, tipo de madera y el bloque desplazado tres píxeles, como una plancha mal calzada. Es el hilo de las calaveras hecho por su oficio y no por su disfraz.",
  letra="Bevan", ancho="+21%", escala="0.93", esquinas="0 px · vivas", peso="~75 KB", horas="Día",
  tokens={"--m-pagina":"#e3ddcd",
   "--m-grano":"repeating-linear-gradient(52deg, rgba(24,20,16,.13) 0 1px, transparent 1px 5px), url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='200' height='200'%3E%3Cfilter id='p'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.85' numOctaves='3'/%3E%3C/filter%3E%3Crect width='200' height='200' filter='url(%23p)'/%3E%3C/svg%3E\")",
   "--m-grano-op":".22","--m-tarjeta":"#efe9da","--m-borde":"2px","--m-borde-color":"#181410",
   "--m-sombra":"3px 3px 0 #181410","--m-r-tarjeta":"0","--m-r-mini":"0","--m-r-barra":"0","--m-r-chip":"0",
   "--m-tinta":"#181410","--m-tinta-2":"#5c5346",
   "--m-acento":"#a32615","--m-acento-velo":"rgba(163,38,21,.13)",
   "--m-aviso":"#6b5200","--m-aviso-velo":"rgba(107,82,0,.14)",
   "--m-peligro":"#181410","--m-peligro-velo":"rgba(24,20,16,.13)","--m-carril":"#cec5b0",
   "--m-icono":"repeating-linear-gradient(45deg,#181410 0 2px,#efe9da 2px 4px)",
   "--m-titulo":'"Bevan",Georgia,serif',"--m-titulo-px":"15px","--m-titulo-peso":"400",
   "--m-cifra":'"Bevan",Georgia,serif',"--m-cifra-peso":"400","--m-cifra-esp":"-.01em",
   "--m-chip-fuente":'"Bevan",Georgia,serif',"--m-chip-esp":".04em","--m-chip-caja":"uppercase",
   "--m-dur":".2s","--m-curva":"steps(6,end)"}),

 dict(id="rotulo", nombre="Rótulo", familia="de-aqui", llave="El de la calle", color="#ff3d8b",
  premisa="Esmalte sobre lámina: el letrero pintado a mano de una fonda o una llantera. Letra gorda con sombra dura y sin difuminar, rosa mexicano sobre azul petróleo, y el brillo del esmalte cruzando en diagonal. La lámina se dobla, así que las esquinas van francamente redondeadas.",
  letra="Bungee", ancho="+39%", escala="0.80", esquinas="16 px · redondeadas", peso="~90 KB", horas="Noche",
  tokens={"--m-pagina":"#0e3040",
   "--m-grano":"linear-gradient(103deg, rgba(255,255,255,.09) 0 16%, transparent 20% 76%, rgba(255,255,255,.05) 82%)",
   "--m-grano-op":"1","--m-tarjeta":"linear-gradient(168deg,#14455a 0%,#0f3548 60%,#134256 100%)",
   "--m-borde":"3px","--m-borde-color":"#f2e7cf",
   "--m-sombra":"4px 4px 0 rgba(0,0,0,.55), inset 0 1px 0 rgba(255,255,255,.14)",
   "--m-r-tarjeta":"16px","--m-r-mini":"999px","--m-r-barra":"999px","--m-r-chip":"999px",
   "--m-tinta":"#fdf6e6","--m-tinta-2":"#a8c2ce","--m-titulo-sombra":"2px 2px 0 rgba(0,0,0,.5)",
   "--m-acento":"#ff3d8b","--m-acento-tinta":"#ffa3cd","--m-acento-velo":"rgba(255,61,139,.17)",
   "--m-aviso":"#ffd447","--m-aviso-velo":"rgba(255,212,71,.16)",
   "--m-peligro":"#ff8a70","--m-peligro-velo":"rgba(255,138,112,.16)","--m-carril":"#0a2634",
   "--m-icono":"radial-gradient(circle at 36% 30%,#ff85b6,#d4145a)",
   "--m-titulo":'"Bungee",Impact,sans-serif',"--m-titulo-px":"13px","--m-titulo-peso":"400",
   "--m-cifra":'"Bungee",Impact,sans-serif',"--m-cifra-peso":"400","--m-cifra-esp":"0",
   "--m-chip-fuente":'"Bungee",Impact,sans-serif',"--m-chip-esp":".03em",
   "--m-dur":".34s","--m-curva":"cubic-bezier(.34,1.5,.64,1)"}),

 dict(id="picado", nombre="Papel picado", familia="de-aqui", llave="El de fiesta", color="#c2145f",
  premisa="Papel de seda calado y colgado a contraluz. Cada tarjeta lleva su banda picada arriba, el fondo son las hileras del tendido y el icono es la rueda de los cuatro colores del papel. Es el único que se siente de fiesta, y para una app que celebra cosas eso no es poco.",
  letra="Fraunces", ancho="+8%", escala="1", esquinas="5 px · casi vivas", peso="~95 KB", horas="Día",
  tokens={"--m-pagina":"#f5eee1",
   "--m-grano":"url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='150' height='90'%3E%3Cg opacity='.5'%3E%3Cpath d='M0 14h150' stroke='%23c8b9a2' stroke-width='1' stroke-dasharray='2 4'/%3E%3Cg fill='%23e6187c' opacity='.16'%3E%3Crect x='6' y='16' width='58' height='40' rx='3'/%3E%3C/g%3E%3Cg fill='%232aa9a0' opacity='.16'%3E%3Crect x='78' y='16' width='58' height='40' rx='3'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E\")",
   "--m-grano-op":"1","--m-tarjeta":"#fffdf8","--m-borde":"1px","--m-borde-color":"#e0d3bd",
   "--m-sombra":"0 6px 16px rgba(120,90,60,.15)",
   "--m-r-tarjeta":"5px","--m-r-mini":"999px","--m-r-barra":"999px","--m-r-chip":"999px",
   "--m-cenefa-alto":"16px",
   "--m-cenefa":"url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='40' height='16'%3E%3Crect width='40' height='16' fill='%23e6187c'/%3E%3Cg fill='%23fffdf8'%3E%3Ccircle cx='10' cy='16' r='7'/%3E%3Ccircle cx='30' cy='16' r='7'/%3E%3Ccircle cx='20' cy='5' r='3.4'/%3E%3Ccircle cx='0' cy='5' r='3.4'/%3E%3Ccircle cx='40' cy='5' r='3.4'/%3E%3C/g%3E%3C/svg%3E\") repeat-x",
   "--m-tinta":"#3a2438","--m-tinta-2":"#7a6070",
   "--m-acento":"#c2145f","--m-acento-velo":"rgba(194,20,95,.11)",
   "--m-aviso":"#7d5a00","--m-aviso-velo":"rgba(125,90,0,.13)",
   "--m-peligro":"#a02a12","--m-peligro-velo":"rgba(160,42,18,.12)","--m-carril":"#e7dcc9",
   "--m-icono":"conic-gradient(#e6187c 0 25%, #2aa9a0 0 50%, #f2a516 0 75%, #6d3fb8 0)",
   "--m-titulo":'"Fraunces",Georgia,serif',"--m-titulo-px":"17px","--m-titulo-peso":"800",
   "--m-cifra":'"Fraunces",Georgia,serif',"--m-cifra-peso":"800","--m-cifra-esp":"-.02em",
   "--m-chip-fuente":'"Fraunces",Georgia,serif',"--m-dur":".5s","--m-curva":"cubic-bezier(.34,1.45,.64,1)"},
  extra=".picado .ficha{ padding-top:26px; }"),

 dict(id="consola", nombre="Consola", familia="de-pantalla", llave="Gratis, siempre", color="#3bff9e",
  premisa="Fósforo sobre negro, todo en monoespaciada, cero adornos y el movimiento a saltos en vez de suave. Es el único que no necesita ni una imagen: la textura son dos líneas de CSS. Y de paso es la red de seguridad para quien no distingue bien los tonos.",
  letra="JetBrains Mono", ancho="+29%", escala="0.86", esquinas="0 px · vivas", peso="~28 KB", horas="Noche",
  tokens={"--m-pagina":"#000",
   "--m-grano":"repeating-linear-gradient(180deg, rgba(120,255,190,.16) 0 1px, transparent 1px 3px)",
   "--m-grano-op":"1","--m-tarjeta":"#050705","--m-borde":"1px","--m-borde-color":"#2f5f47",
   "--m-sombra":"none","--m-r-tarjeta":"0","--m-r-mini":"0","--m-r-barra":"0","--m-r-chip":"0",
   "--m-tinta":"#c9ffe4","--m-tinta-2":"#5f9a7d",
   "--m-acento":"#3bff9e","--m-acento-velo":"rgba(59,255,158,.12)",
   "--m-aviso":"#ffd447","--m-aviso-velo":"rgba(255,212,71,.12)",
   "--m-peligro":"#ff6b52","--m-peligro-velo":"rgba(255,107,82,.12)","--m-carril":"#10291d",
   "--m-icono":"#3bff9e",
   "--m-titulo":'"JetBrains Mono",ui-monospace,monospace',"--m-titulo-px":"13px","--m-titulo-peso":"700",
   "--m-cifra":'"JetBrains Mono",ui-monospace,monospace',"--m-cifra-peso":"700","--m-cifra-esp":"-.04em",
   "--m-chip-fuente":'"JetBrains Mono",ui-monospace,monospace',"--m-chip-esp":".06em","--m-chip-caja":"uppercase",
   "--m-dur":".12s","--m-curva":"steps(12, end)"}),

 dict(id="neon", nombre="Neón", familia="de-pantalla", llave="Todo redondo", color="#3febff",
  premisa="Un tubo de neón es vidrio DOBLADO, así que aquí todo es redondo — la tarjeta, la barra, las pastillas. Cian sobre asfalto mojado, con el resplandor por dentro y por fuera del trazo. El aviso pasa a ámbar y el peligro a rosa encendido: cambian de tono y siguen diciendo lo mismo.",
  letra="Baloo 2", ancho="−2%", escala="1", esquinas="Redondas del todo", peso="~60 KB", horas="Noche",
  tokens={"--m-pagina":"#08060f",
   "--m-grano":"radial-gradient(ellipse at 22% 12%, rgba(255,45,150,.2), transparent 55%), radial-gradient(ellipse at 82% 78%, rgba(60,235,255,.16), transparent 52%)",
   "--m-grano-op":"1","--m-tarjeta":"linear-gradient(170deg,#141024 0%,#0d0a18 100%)",
   "--m-borde":"2px","--m-borde-color":"#3febff",
   "--m-sombra":"0 0 0 1px rgba(63,235,255,.28), 0 0 18px rgba(63,235,255,.34), inset 0 0 16px rgba(63,235,255,.12)",
   "--m-halo":"0 0 10px rgba(63,235,255,.75)",
   "--m-r-tarjeta":"999px","--m-r-mini":"999px","--m-r-barra":"999px","--m-r-chip":"999px",
   "--m-tinta":"#eafcff","--m-tinta-2":"#8fb8c4","--m-titulo-sombra":"0 0 12px rgba(63,235,255,.6)",
   "--m-acento":"#3febff","--m-acento-tinta":"#7df3ff","--m-acento-velo":"rgba(63,235,255,.14)",
   "--m-aviso":"#ffc24d","--m-aviso-velo":"rgba(255,194,77,.15)",
   "--m-peligro":"#ff5f8f","--m-peligro-velo":"rgba(255,95,143,.15)","--m-carril":"#191430",
   "--m-icono":"radial-gradient(circle at 38% 34%, #ff8fc4, #ff2d96 62%, #7a0f47)",
   "--m-titulo":'"Baloo 2",system-ui,sans-serif',"--m-titulo-px":"15px","--m-titulo-peso":"700",
   "--m-cifra":'"Baloo 2",system-ui,sans-serif',"--m-cifra-peso":"700","--m-cifra-esp":"-.01em",
   "--m-chip-fuente":'"Baloo 2",system-ui,sans-serif',"--m-dur":".9s","--m-curva":"cubic-bezier(.18,.9,.3,1)"},
  extra=".neon .ficha{ padding:16px 22px; }"),

 dict(id="cyber", nombre="Cyberpunk", familia="de-pantalla", llave="Visor, no marco", color="#00f0ff",
  premisa="El otro cyberpunk: no el letrero, sino el VISOR. La tarjeta no lleva marco cerrado —lleva cuatro escuadras y una regla de marcas arriba, como una mira—, la esquina de abajo va cortada en chaflán de verdad, y el título sale desdoblado en cian y magenta como una señal mal sincronizada. Un marco cerrado es una app; cuatro escuadras es un aparato.",
  letra="Chakra Petch", ancho="+4%", escala="1", esquinas="0 px + chaflán", peso="~70 KB", horas="Noche",
  tokens={"--m-pagina":"#05070c",
   "--m-grano":"repeating-linear-gradient(180deg, rgba(0,240,255,.06) 0 1px, transparent 1px 4px), radial-gradient(ellipse at 78% 18%, rgba(255,47,142,.16), transparent 58%)",
   "--m-grano-op":"1","--m-tarjeta":"linear-gradient(180deg,#0b1018 0%,#070a10 100%)",
   "--m-borde":"0","--m-borde-color":"transparent","--m-sombra":"none",
   "--m-r-tarjeta":"0","--m-r-mini":"0","--m-r-barra":"0","--m-r-chip":"0",
   "--m-tinta":"#dffbff","--m-tinta-2":"#6f97a6",
   "--m-titulo-sombra":"1.5px 0 0 rgba(255,47,142,.85), -1.5px 0 0 rgba(0,240,255,.85)",
   "--m-acento":"#00f0ff","--m-acento-velo":"rgba(0,240,255,.12)",
   "--m-aviso":"#ffd21f","--m-aviso-velo":"rgba(255,210,31,.13)",
   "--m-peligro":"#ff2f8e","--m-peligro-velo":"rgba(255,47,142,.14)","--m-carril":"#0f1a24",
   "--m-icono":f'url("{svg("hud-reticula.svg")}") center/contain no-repeat',
   "--m-titulo":'"Chakra Petch",system-ui,sans-serif',"--m-titulo-px":"15px","--m-titulo-peso":"700","--m-titulo-esp":".04em","--m-titulo-caja":"uppercase",
   "--m-cifra":'"Chakra Petch",system-ui,sans-serif',"--m-cifra-peso":"700","--m-cifra-esp":"0",
   "--m-chip-fuente":'"Chakra Petch",system-ui,sans-serif',"--m-chip-esp":".1em","--m-chip-caja":"uppercase",
   "--m-dur":".18s","--m-curva":"steps(9,end)"},
  extra=""".cyber .ficha{
    background-image:url("%s"), linear-gradient(180deg,#0b1018 0%%,#070a10 100%%);
    background-size:100%% 100%%, auto; background-repeat:no-repeat;
    clip-path:polygon(0 0, 100%% 0, 100%% calc(100%% - 14px), calc(100%% - 14px) 100%%, 0 100%%);
    padding:20px 18px 18px;
  }""" % svg("hud-esquinas.svg")),

 dict(id="plano", nombre="Blueprint", familia="de-pantalla", llave="Nada está terminado", color="#9fd0ff",
  premisa="El plano azul de toda la vida: retícula de dos pesos, cotas con puntas de flecha y marcas de sección. Aquí la tarjeta no es una tarjeta: es una PIEZA ACOTADA, con su línea de medida cruzando por encima y el hueco donde iría la cifra. Dice algo que ningún otro mundo dice — que lo tuyo todavía se está construyendo.",
  letra="Rajdhani", ancho="−10%", escala="1", esquinas="0 px · vivas", peso="~65 KB", horas="Noche",
  tokens={"--m-pagina":"#0d2b52",
   "--m-grano":f'url("{svg("plano-rejilla.svg")}")',"--m-grano-op":"1",
   "--m-tarjeta":"rgba(255,255,255,.035)","--m-borde":"1px","--m-borde-color":"#5e93cc",
   "--m-sombra":"inset 0 0 0 4px rgba(13,43,82,.7), inset 0 0 0 5px rgba(94,147,204,.45)",
   "--m-r-tarjeta":"0","--m-r-mini":"0","--m-r-barra":"0","--m-r-chip":"0",
   "--m-cenefa-alto":"26px","--m-cenefa":f'url("{svg("plano-cota.svg")}") center/200px 26px no-repeat',
   "--m-tinta":"#eaf4ff","--m-tinta-2":"#8fb6db",
   "--m-acento":"#9fd0ff","--m-acento-velo":"rgba(159,208,255,.13)",
   "--m-aviso":"#ffd98a","--m-aviso-velo":"rgba(255,217,138,.14)",
   "--m-peligro":"#ff9c86","--m-peligro-velo":"rgba(255,156,134,.14)","--m-carril":"rgba(159,208,255,.16)",
   "--m-icono":f'url("{svg("plano-marca.svg")}") center/contain no-repeat',
   "--m-titulo":'"Rajdhani",system-ui,sans-serif',"--m-titulo-px":"17px","--m-titulo-peso":"700","--m-titulo-esp":".03em",
   "--m-cifra":'"Rajdhani",system-ui,sans-serif',"--m-cifra-peso":"700","--m-cifra-esp":"0",
   "--m-chip-fuente":'"Rajdhani",system-ui,sans-serif',"--m-chip-esp":".1em","--m-chip-caja":"uppercase",
   "--m-dur":".4s","--m-curva":"cubic-bezier(.4,0,.2,1)"},
  extra=".plano .ficha{ padding-top:36px; }"),

 dict(id="forja", nombre="Forja", familia="de-materia", llave="El buque insignia", color="#ff9d3d",
  premisa="Hierro golpeado con la brasa todavía dentro: banda remachada arriba —remaches a intervalos irregulares, que uno cada 16 px exactos parece tornillería de mueble— y una voluta de herrería en la esquina, de esas que salen cuando al herrero le sobra hierro. Esquina viva en todo y la letra grabada en vez de escrita.",
  letra="Cinzel", ancho="+28%", escala="0.88", esquinas="0 px · vivas", peso="~180 KB", horas="Noche",
  tokens={"--m-pagina":"#16110c",
   "--m-grano":"url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='180' height='180'%3E%3Cfilter id='f'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.035 0.09' numOctaves='4'/%3E%3C/filter%3E%3Crect width='180' height='180' filter='url(%23f)'/%3E%3C/svg%3E\")",
   "--m-grano-op":".16","--m-tarjeta":"linear-gradient(163deg, #2a2016 0%, #1d1710 55%, #241b13 100%)",
   "--m-borde":"3px","--m-borde-color":"#6b5636",
   "--m-marco":"linear-gradient(150deg,#8a6f3f,#d8b978 18%,#3a2e1c 48%,#a08551 78%,#40331e) 1",
   "--m-sombra":"inset 0 1px 0 rgba(255,214,150,.13), 0 10px 24px rgba(0,0,0,.5)",
   "--m-r-tarjeta":"0","--m-r-mini":"0","--m-r-barra":"0","--m-r-chip":"0",
   "--m-cenefa-alto":"14px","--m-cenefa":f'url("{svg("forja-remaches.svg")}") repeat-x',
   "--m-tinta":"#f2e3ce","--m-tinta-2":"#a99372",
   "--m-acento":"#ff9d3d","--m-acento-velo":"rgba(255,157,61,.15)",
   "--m-aviso":"#f5d76e","--m-aviso-velo":"rgba(245,215,110,.15)",
   "--m-peligro":"#ff8a70","--m-peligro-velo":"rgba(255,138,112,.15)","--m-carril":"#3a2d1d",
   "--m-icono":"linear-gradient(150deg,#c98a3a,#8a5622)",
   "--m-titulo":'"Cinzel",Georgia,serif',"--m-titulo-px":"14px","--m-titulo-peso":"700","--m-titulo-esp":".04em",
   "--m-cifra":'"Cinzel",Georgia,serif',"--m-cifra-peso":"700","--m-cifra-esp":"0",
   "--m-chip-fuente":'"Cinzel",Georgia,serif',"--m-chip-esp":".07em",
   "--m-dur":"1.1s","--m-curva":"cubic-bezier(.16,.84,.28,1)"},
  extra=""".forja .ficha{ padding-top:26px; }
  .forja .ficha::after{
    content:""; position:absolute; right:-2px; bottom:-2px; width:46px; height:46px;
    background:url("%s") center/contain no-repeat; transform:scaleX(-1) rotate(-90deg);
    transform-origin:center; pointer-events:none; opacity:.9;
  }""" % svg("forja-voluta.svg")),

 dict(id="obsidiana", nombre="Obsidiana", familia="de-materia", llave="El oscuro elegante", color="#3fd0c9",
  premisa="Vidrio volcánico partido: planos que cambian de tono, un filo claro donde pega la luz y un destello verde azulado al fondo. Todo con la esquina viva, porque la obsidiana se rompe en filo y no en curva. Es lo contrario de Forja, que era el oscuro con fuerza.",
  letra="Bodoni Moda", ancho="+6%", escala="1", esquinas="0 px · vivas", peso="~85 KB", horas="Noche",
  tokens={"--m-pagina":"#07080a",
   "--m-grano":"linear-gradient(118deg, rgba(63,208,201,.07) 0 30%, transparent 34% 66%, rgba(140,120,255,.06) 72%)",
   "--m-grano-op":"1","--m-tarjeta":"linear-gradient(124deg,#15191f 0 34%,#0b0e12 34% 63%,#12161d 63%)",
   "--m-borde":"1px","--m-borde-color":"#2b333d",
   "--m-sombra":"inset 0 1px 0 rgba(190,240,240,.16), 0 14px 34px rgba(0,0,0,.6)",
   "--m-r-tarjeta":"0","--m-r-mini":"0","--m-r-barra":"0","--m-r-chip":"0",
   "--m-tinta":"#e8f2f3","--m-tinta-2":"#8fa0a8",
   "--m-acento":"#3fd0c9","--m-acento-velo":"rgba(63,208,201,.13)",
   "--m-aviso":"#f5d76e","--m-aviso-velo":"rgba(245,215,110,.14)",
   "--m-peligro":"#ff8a70","--m-peligro-velo":"rgba(255,138,112,.14)","--m-carril":"#1a2026",
   "--m-icono":"linear-gradient(128deg,#3fd0c9 0 42%,#0f4f52 42%)",
   "--m-titulo":'"Bodoni Moda",Didot,Georgia,serif',"--m-titulo-px":"17px","--m-titulo-peso":"700","--m-titulo-esp":".01em",
   "--m-cifra":'"Bodoni Moda",Didot,Georgia,serif',"--m-cifra-peso":"700","--m-cifra-esp":"-.01em",
   "--m-chip-fuente":'"Bodoni Moda",Didot,Georgia,serif',"--m-chip-esp":".08em","--m-chip-caja":"uppercase",
   "--m-dur":"1.2s","--m-curva":"cubic-bezier(.2,.9,.25,1)"}),

 dict(id="vitral", nombre="Vitral", familia="de-materia", llave="El más caro de hacer", color="#ffd98a",
  premisa="Plomo, vidrio de color y un filo de pan de oro. Los ocho colores que elige el usuario dejan de ser etiquetas y pasan a ser paneles de cristal. Es el que mejor le sienta al árbol de talentos, porque un árbol de vidrio emplomado ya es un dibujo.",
  letra="Marcellus", ancho="−1%", escala="1", esquinas="3 px · casi vivas", peso="~240 KB", horas="Noche",
  tokens={"--m-pagina":"#0c1030",
   "--m-grano":"radial-gradient(circle at 30% 18%, rgba(120,150,255,.2), transparent 55%), radial-gradient(circle at 78% 72%, rgba(255,190,90,.13), transparent 50%)",
   "--m-grano-op":"1","--m-tarjeta":"linear-gradient(158deg, #191f4c 0%, #12163a 60%, #1c1f52 100%)",
   "--m-borde":"4px","--m-borde-color":"#3a3f6b",
   "--m-marco":"linear-gradient(140deg,#2a2e55,#8f97c8 20%,#1a1d3d 42%,#d8bd7e 58%,#6f77a8 78%,#20244a) 1",
   "--m-sombra":"inset 0 0 0 1px rgba(210,180,110,.34), 0 12px 30px rgba(0,0,0,.5)",
   "--m-r-tarjeta":"3px","--m-r-mini":"3px","--m-r-barra":"0","--m-r-chip":"3px",
   "--m-tinta":"#eae7ff","--m-tinta-2":"#9a9ccb",
   "--m-acento":"#ffd98a","--m-acento-velo":"rgba(255,217,138,.14)",
   "--m-aviso":"#f5d76e","--m-aviso-velo":"rgba(245,215,110,.15)",
   "--m-peligro":"#ff8a70","--m-peligro-velo":"rgba(255,138,112,.15)","--m-carril":"#262b58",
   "--m-icono":"linear-gradient(150deg,#7d5cff,#2f3fa8)",
   "--m-titulo":'"Marcellus",Georgia,serif',"--m-titulo-px":"16px","--m-titulo-peso":"400","--m-titulo-esp":".03em",
   "--m-cifra":'"Marcellus",Georgia,serif',"--m-cifra-peso":"400","--m-cifra-esp":"0",
   "--m-chip-fuente":'"Marcellus",Georgia,serif',"--m-chip-esp":".09em","--m-chip-caja":"uppercase",
   "--m-dur":"1.4s","--m-curva":"cubic-bezier(.22,1,.36,1)"}),
]

FAMILIAS = [
 ("de-aqui","De aquí","Materiales que se pueden tocar en este país. Es el hilo que ningún paquete de temas genérico puede copiar."),
 ("de-pantalla","De pantalla","No imitan una materia: imitan un aparato. Son los más baratos de todos porque casi no llevan imagen."),
 ("de-materia","De materia","Piedra, metal y vidrio. Los oscuros con cuerpo, y los más caros de hacer bien."),
]
